/* CRIANDO UM BANCO */

CREATE DATABASE SAPIENS_DB1;

/* CONECTANDO */

USE SAPIENS_DB1;

/* CRIANDO A TABELA */

CREATE TABLE ALUNO(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	CURSO VARCHAR(40)
);

/*INSERINDO OS DADOS*/

INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('SHIRLANE','F','SENADOR SOARES - CENTRO - RIO DE BRANCO - AC','947665696',887774856,'ENGENHARIA DA COMPUTAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('MATHEUS','M','AV. JORGE TEIXEIRA INDUSTRIAL - PORTO VELHO - RO','8477665696',886664856,'ENGENHARIA DA COMPUTAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('APARECIDO','M','JUAZEIRO - T.NEVES - PORTO VELHO - RO','967654696',994444856,'SISTEMAS DE INFORMAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF, EMAIL,CURSO) VALUES('ROSA','F','SENADOR SOARES - CENTRO - RIO DE BRANCO - AC','654665696',887776549,'rosa@gmail.com','JOGOS DIGITAIS');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('ROBERTA','F','AV. PAULISTA - VILA MARIA - SÃO PAULO - SP','947665696',887774856,'SISTEMAS DE INFORMAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF, EMAIL,CURSO) VALUES('RODRIGO','M','R. 21 DE ABRIL - CENTRO - JI-PARANÁ - RO','654667543',882226549,'rodrigosa@gmail.com','ENGENHARIA DA COMPUTAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF, EMAIL,CURSO) VALUES('HELOISA','F','R. DAS FLORES - ESPERANÇA DA COMUNIDADE - PORTO VELHO - RO','456765696',1234776549,'helloisa@gmail.com','SISTEMAS DE INFORMAÇÃO');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF, EMAIL,CURSO) VALUES('RICARDO','M','AV. BRASIL - 2º DISTRITO - JI-PARANÁ - RO','654661213',852226549,'ricardo_rosa@gmail.com','JOGOS DIGITAIS');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('MERCEDES','F','R. DAS NEVES - CENTRO - PORTO VELHO - RO','947665696',887774856,'JOGOS DIGITAIS');
INSERT INTO ALUNO (NOME,SEXO,ENDERECO,TELEFONE,CPF,CURSO) VALUES('LUCAS','M','SENADOR SOARES - CENTRO - RIO DE BRANCO - AC','948665696',887771234,'SISTEMAS DE INFORMAÇÃO');